/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author quinglaess
 */
public class Frame extends javax.swing.JFrame
{
    static String dnaStr;
    /**
     * Creates new form frame
     */
    public Frame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jlabDna = new javax.swing.JLabel();
        jTextDnaFld = new javax.swing.JTextField();
        jBtnDnaConvert = new javax.swing.JButton();
        jTextMrnaFld = new javax.swing.JTextField();
        jBtnMrnaConvert = new javax.swing.JButton();
        jTextAmino = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DNA Converter");
        setMaximumSize(new java.awt.Dimension(1474, 1474));
        setMinimumSize(new java.awt.Dimension(350, 215));

        jlabDna.setText("Enter DNA here");

        jTextDnaFld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextDnaFld.setText("DNA");
        jTextDnaFld.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextDnaFld.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextDnaFldActionPerformed(evt);
            }
        });
        jTextDnaFld.addInputMethodListener(new java.awt.event.InputMethodListener()
        {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt)
            {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt)
            {
                jTextDnaFldCaretPositionChanged(evt);
            }
        });

        jBtnDnaConvert.setText("Convert to mRNA ");
        jBtnDnaConvert.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnDnaConvertActionPerformed(evt);
            }
        });

        jTextMrnaFld.setText("mRNA");
        jTextMrnaFld.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextMrnaFldActionPerformed(evt);
            }
        });

        jBtnMrnaConvert.setText("Convert to amino acids");
        jBtnMrnaConvert.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnMrnaConvertActionPerformed(evt);
            }
        });

        jTextAmino.setText("Amino acids");
        jTextAmino.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextAminoActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Include start and stop codons");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextDnaFld)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextAmino)
                    .add(jTextMrnaFld)
                    .add(layout.createSequentialGroup()
                        .add(jlabDna)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 282, Short.MAX_VALUE)
                        .add(jCheckBox1))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jBtnMrnaConvert)
                            .add(jBtnDnaConvert))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlabDna)
                    .add(jCheckBox1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextDnaFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jBtnDnaConvert)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextMrnaFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jBtnMrnaConvert)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextAmino, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDnaConvertActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnDnaConvertActionPerformed
    {//GEN-HEADEREND:event_jBtnDnaConvertActionPerformed
                                this.jTextAmino.setText("");
				String dna = jTextDnaFld.getText();
				dna = dna.replace("g","C");
				dna = dna.replace("c","G");
				dna = dna.replace("a","u");
				dna = dna.replace("t","a");
				dna = dna.toLowerCase();
				dnaStr = dna;
		        
				jTextMrnaFld.setText(dnaStr);
    }//GEN-LAST:event_jBtnDnaConvertActionPerformed

    private void jBtnMrnaConvertActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnMrnaConvertActionPerformed
    {//GEN-HEADEREND:event_jBtnMrnaConvertActionPerformed
        String dna = dnaStr;
        String[] dnaArray = dna.split(" ");

            String[][] names = { {"phenylanine", "uuu", "uuc"},
                                 {"leucine", "uua", "uug", "cuu", "cuc", "cua", "cug"},
                                 {"isoleucine", "auu", "auc", "aua"},
                                 {"initiation codon", "aug"},
                                 {"valine", "guu", "guc", "gua", "gug"},
                                 {"serine", "ucu", "ucc", "uca", "ucg"},
                                 {"proline", "ccu", "ccc", "cca", "ccg"},
                                 {"threonine", "acu", "acc", "aca", "acg"},
                                 {"alanine", "gcu", "gcc", "gca", "gcg"},
                                 {"tryosine", "uau", "uac"},
                                 {"stop codon", "uaa", "uag", "uga"},
                                 {"histidine", "cau", "cac"},
                                 {"glutamine","caa","cag"},
                                 {"asparagine", "aau", "aac"},
                                 {"lysine", "aaa", "aag"},
                                 {"glycine", "ggg", "gga", "ggu", "ggc"} };
            for (int x = 0; x < dnaArray.length; x++)
            {
                for (int i = 0; i < names.length; i++)
                {
                    String replacement = names[i][0];
                    for (int y = 1; y < names[i].length; y++)
                    {
                        if (dnaArray[x].equals(names[i][y]))
                            dnaArray[x] = replacement;
                    }
                }
            }


            String built = "";
            for (int i = 0; i < dnaArray.length; i++)
            {
                    built = built + dnaArray[i];

                    if (i != dnaArray.length - 1)
                            built = built + ", ";
            }
            jTextAmino.setText(built);

    }//GEN-LAST:event_jBtnMrnaConvertActionPerformed

    private void jTextMrnaFldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextMrnaFldActionPerformed
    {//GEN-HEADEREND:event_jTextMrnaFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMrnaFldActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBox1ActionPerformed
    {//GEN-HEADEREND:event_jCheckBox1ActionPerformed
        jTextDnaFld.setText("tac DNA act");        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextDnaFldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextDnaFldActionPerformed
    {//GEN-HEADEREND:event_jTextDnaFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDnaFldActionPerformed

    private void jTextDnaFldCaretPositionChanged(java.awt.event.InputMethodEvent evt)//GEN-FIRST:event_jTextDnaFldCaretPositionChanged
    {//GEN-HEADEREND:event_jTextDnaFldCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDnaFldCaretPositionChanged

    private void jTextAminoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextAminoActionPerformed
    {//GEN-HEADEREND:event_jTextAminoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAminoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDnaConvert;
    private javax.swing.JButton jBtnMrnaConvert;
    private javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JTextField jTextAmino;
    public javax.swing.JTextField jTextDnaFld;
    public javax.swing.JTextField jTextMrnaFld;
    private javax.swing.JLabel jlabDna;
    // End of variables declaration//GEN-END:variables
}
